### ISSUE TITLE
Colors aren't working.

### ISSUE THREAD

**Issue by danhollick** [jamesmcallister/tachyons-for-styled-components#5]
At least for me they aren't.
All other properties seem to work fine, but no colors at all. 
Not even working with the readme example.

**Comment by jamesmcallister** [comment]
Sorry, the readme is a bit lacking. I need rewrite it.
Colours need to be defined in css as variables.
```css
/* variables.css */
:root {
  --black: #000;
  --near-black: #111;
  --dark-gray:#333;
  --mid-gray:#555;
  --gray: #777;
  --silver: #999;
  --light-silver: #aaa;
  --moon-gray: #ccc;
  --light-gray: #eee;
  --near-white: #f4f4f4;
  --white: #fff;
}
```
Here is the create-react-app app.js file.

```jsx
// app.js
import React, {Component} from 'react';
import logo from './logo.svg';
import tachyons from 'styled-components-tachyons';
import styled, {keyframes} from 'styled-components';
import './variables.css'

const rotate360 = keyframes`
  from { transform: rotate(0deg);}
  to { transform: rotate(360deg);}
`;

const Wrapper = styled.div`
  ${tachyons}

`;
const AppLogo = styled.img`
  ${tachyons}
  animation: ${rotate360} infinite 20s linear
}
`;
const AppIntro = styled.p`
  ${tachyons}
`;

class App extends Component {
  render() {
    return (
      <Wrapper tc>
        <div >
          <AppLogo h3 src={logo} alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <AppIntro f3>
          To get started, edit <code>src/App.js</code> and save to reload.
        </AppIntro>
      </Wrapper>
    );
  }
}

export default App;
```
